### ISSUE TITLE
[DatabaseApp] Где MVVM?

### ISSUE THREAD

**Issue by pavel-b-novikov** [Irina-Korsun/nsudotnet#4]
Ирина, вы точно читали условия задачи?
Где MVVM? Почему исходники в MainWindow.xaml? 
Это в лучшем случае может претендовать на трояк.

**Comment by Irina-Korsun** [comment]
Переделаю, уберу

**Comment by pavel-b-novikov** [comment]
Ну и особо ничего не изменилось. Сборки с логикой по-прежнему нет. DAL и логика свалены в одно (sic!) консольное приложение.

**Comment by pavel-b-novikov** [comment]
MVVM-фреймворк не используется, как я предупреждал в условиях. Весь код в .xaml.cs, чего быть категорически не должно

**Comment by pavel-b-novikov** [comment]
В общем задача реализована не по requirement-ам. Принять такое за полноценную задачу я не могу.

**Comment by pavel-b-novikov** [comment]
Максимум - 5 баллов, то бишь трояк. Не обессудьте. Зато без доп. вопросов.

**Comment by Irina-Korsun** [comment]
Окаайй

**Comment by Irina-Korsun** [comment]
А можно через кого-то зачетку передать?) а то в город как то не оч потом поздно ехать(
